version = "1.0"

[main]
name.en = "Configuration panel"
name.fr = "Panneau de configuration"
services = ["__APP__"]

[main.server]
name.en = "Use this node as server"

[main.server.enable_transport]
ask = "Use as server"
type = "boolean"
bind = "reticulum>enable_transport:__INSTALL_DIR__/.__APP__/config"

[main.server.backbone_listen_enabled]
ask = "Use backbone interface"
type = "boolean"
bind = "Backbone_Listener>enabled:__INSTALL_DIR__/.__APP__/config"

[main.server.backbone_listen_on]
ask = "Backbone listen on"
type = "string"
bind = "Backbone_Listener>listen_on:__INSTALL_DIR__/.__APP__/config"
default = "0.0.0.0"

[main.server.backbone_port]
ask = "Backbone port"
type = "number"
readonly = true
bind = "Backbone_Listener>port:__INSTALL_DIR__/.__APP__/config"

[main.server.tcp_server_enabled]
ask = "Use TCP interface"
type = "boolean"
bind = "TCP_Server_Interface>enabled:__INSTALL_DIR__/.__APP__/config"

[main.server.tcp_listen_on]
ask = "TCP listen on"
type = "string"
bind = "TCP_Server_Interface>listen_ip:__INSTALL_DIR__/.__APP__/config"
default = "0.0.0.0"

[main.server.tcp_port]
ask = "TCP port"
type = "number"
readonly = true
bind = "TCP_Server_Interface>listen_port:__INSTALL_DIR__/.__APP__/config"

[main.client]
name = "Use as client"

[main.client.backbone_remote_enabled]
ask = "Use backbone interface for client"
type = "boolean"
bind = "Backbone_Remote>enabled:__INSTALL_DIR__/.__APP__/config"
optional = true

[main.client.backbone_remote_target]
ask = "Backbone remote target"
type = "string"
bind = "Backbone_Remote>remote:__INSTALL_DIR__/.__APP__/config"
optional = true
default = "127.0.0.1"

[main.client.backbone_remote_target_port]
ask = "Backbone remote target port"
type = "number"
bind = "Backbone_Remote>target_port:__INSTALL_DIR__/.__APP__/config"
optional = true
default = "4242"

[main.client.tcp_client_enabled]
ask = "Use TCP interface for client"
type = "boolean"
bind = "TCP_Client_Interface>enabled:__INSTALL_DIR__/.__APP__/config"
optional = true

[main.client.tcp_client_target_host]
ask = "TCP listen on"
type = "string"
bind = "TCP_Client_Interface>target_host:__INSTALL_DIR__/.__APP__/config"
optional = true
default = "127.0.0.1"

[main.client.tcp_client_target_port]
ask = "TCP client target port"
type = "number"
bind = "TCP_Client_Interface>target_port:__INSTALL_DIR__/.__APP__/config"
optional = true
default = "4242"

[main.rnsh]
name.en = "RNSH access"
name.fr = "Accès SFTP"
[main.rnsh.rnsh_enable]
ask.fr = "Activer le service RNSH"
ask.en = "Enable RNSH service"
help.fr = "NB: Le service RNSH est arrêté après une mise à jour, une restauration ou un changement d'URL de l'application."
help.en = "NB: The RNSH service is stopped after an upgrade, restore, or URL change."
type = "boolean"
bind = "null"

[main.rnsh.allowed_hosts]
ask = "Add the allowed identities"
type = "text"
bind = "__INSTALL_DIR__/.rnsh/allowed_identities"


[main.tcp_shared]
name.en = "Use TCP for shared instance"
name.fr = "Use TCP for shared instance"
help = "Some platforms don't support domain sockets. You can use instead CP for shared instance."
[main.tcp_shared.tcp_shared_instance]
ask.fr = "Activer TCP shared instance"
ask.en = "Enable TCP shared instance"
type = "boolean"
