#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
ynh_abort_if_errors


run__open_close_ports() {
    if [[ "$backbone_listen_enabled" == "1" ]]; then
        yunohost firewall allow Both "$port_backbone"
    else
        yunohost firewall disallow Both "$port_backbone"
    fi

    if [[ "$tcp_server_enabled" == "1" ]]; then
        yunohost firewall allow TCP "$port_tcp"
    else
        yunohost firewall disallow TCP "$port_tcp"
    fi
}

ynh_app_config_apply() {
    _ynh_app_config_apply
    run__open_close_ports
}

#=================================================

ynh_app_config_run $1
