#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
ynh_abort_if_errors

#=================================================
# OPEN / CLOSE PORTS
#=================================================

run__open_close_ports() {
    if [[ "$backbone_listen_enabled" == "1" ]]; then
        yunohost firewall allow Both "$port_backbone"
    else
        yunohost firewall disallow Both "$port_backbone"
    fi

    if [[ "$tcp_server_enabled" == "1" ]]; then
        yunohost firewall allow TCP "$port_tcp"
    else
        yunohost firewall disallow TCP "$port_tcp"
    fi
}


#=================================================
# START / STOP RNSH
#=================================================

get__rnsh_enable() {
    if systemctl is-active --quiet "$app-rnsh"; then
        echo "true"
    else
        echo "false"
    fi
}
set__rnsh_enable() {
    if [ "$rnsh_enable" == "1" ]; then
        ynh_systemctl --service="$app-rnsh" --action="start"
        ynh_app_setting_set --key="rnsh_enable" --value=true
    else
        ynh_systemctl --service="$app-rnsh" --action="stop"
        ynh_app_setting_set --key="rnsh_enable" --value=false
    fi
}

ynh_app_config_apply() {
    _ynh_app_config_apply
    run__open_close_ports
}

#=================================================

ynh_app_config_run $1
