#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers


#=================================================
# INSTALLATION
#=================================================

pushd $install_dir
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_exec_as_app "$install_dir/venv/bin/pip" install rns
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================


ynh_config_add_systemd


yunohost service add "$app" --description="Reticulum" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"
yunohost firewall allow TCP "$port"

    ynh_config_add --jinja --template=config.j2 --destination="$install_dir/.$app/config"

ynh_systemctl --service="$app" --action="restart"

    identity=$(ynh_exec_as_app rnsh -p 2>&1 | grep '^Identity')



#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
