#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers


#=================================================
# INSTALLATION
#=================================================

pushd $install_dir
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_exec_as_app "$install_dir/venv/bin/pip" install rns
    mkdir -p "$install_dir/.reticulum"
    chown "$app:$app" "$install_dir/.reticulum"
    ynh_config_add --jinja --template=config.j2 --destination="$install_dir/.reticulum/config"
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================


ynh_config_add_systemd


yunohost service add "$app" --description="Reticulum" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"
yunohost firewall allow TCP "$port"

pushd $install_dir
    identity=$(ynh_exec_as_app "$install_dir/venv/bin/rnsh" -p 2>&1 | grep '^Identity')
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
