#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"
chown -R "$app:$app" "$install_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="Reticulum" --log="/var/log/$app/$app.log"

if [ "$lxmf" == "1" ]; then
ynh_restore "/etc/systemd/system/$app-lxmf.service"
systemctl enable "$app-lxmf.service" --quiet
yunohost service add "$app" --description="Reticulum LXMF Daemon" --log="/var/log/$app/$app.log"
fi

ynh_restore "/etc/systemd/system/$app-rnsh.service"


mkdir -p "/var/log/"$app""
ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RELOAD THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start"
if [ "$lxmf" == "1" ]; then
ynh_systemctl --service="$app-lxmf" --action="start"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
