#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_app_setting_set --app=$app --key=rnsh_enable --value=false 

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="$app-rnsh" --action="stop" --log_path="systemd"

if [ "$lxmf" == "1" ]; then
    ynh_systemctl --service="$app-lxmf" --action="stop"
fi

#=================================================
# UPGRADE
#=================================================

pushd $install_dir
  	ynh_safe_rm "$install_dir/venv"
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_hide_warnings $install_dir/venv/bin/pip install --upgrade pip
    ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade rns==$(ynh_app_upstream_version)

if [ "$lxmf" == "1" ]; then
    ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade lxmf==$(ynh_app_upstream_version)
fi
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================


ynh_config_add_systemd
yunohost service add "$app" --description="Reticulum" --log="/var/log/$app/$app.log"

ynh_config_add_systemd --service="$app-rnsh" --template="rnsh.service"

if [ "$lxmf" == "1" ]; then
ynh_config_add_systemd --service="$app-lxmf" --template="lxmf.service"
yunohost service add "$app-lxmf" --description="Reticulum LXMF Daemon" --log="/var/log/$app/lxmf.log"
fi

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"
if [ "$lxmf" == "1" ]; then
ynh_systemctl --service="$app-lxmf" --action="start"
fi
#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
