#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_app_setting_set --app=$app --key=rnsh_enable --value=false 

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="$app-rnsh" --action="stop" --log_path="systemd"

#=================================================
# UPGRADE
#=================================================

pushd $install_dir
	ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade rns
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================


ynh_config_add_systemd
yunohost service add "$app" --description="Reticulum" --log="/var/log/$app/$app.log"

ynh_config_add_systemd --service="$app-rnsh" --template="rnsh.service"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================


ynh_config_add_systemd

yunohost service add "$app" --description="Reticulum" --log="/var/log/$app/$app.log"


#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
